# Generated by Django 4.0.4 on 2022-06-19 11:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
