# Generated by Django 4.0.4 on 2022-06-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0004_business_image_post_image_alter_business_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='image',
        ),
    ]
